/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AuthProfileState {
  state_json: string;
  state_key: string;
  updated_at: number;
}

export interface AuthProfileStore {
  store_json: string;
  store_key: string;
  updated_at: number;
}

export interface CacheEntries {
  blob: Uint8Array | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface MemoryEmbeddingCache {
  dims: number | null;
  embedding: string;
  hash: string;
  model: string;
  provider: string;
  provider_key: string;
  updated_at: number;
}

export interface MemoryIndexChunks {
  embedding: string;
  end_line: number;
  hash: string;
  id: string | null;
  model: string;
  path: string;
  source: Generated<string>;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryIndexMeta {
  key: string | null;
  value: string;
}

export interface MemoryIndexSources {
  hash: string;
  mtime: number;
  path: string;
  size: number;
  source: Generated<string>;
}

export interface MemoryIndexState {
  id: Generated<number>;
  revision: number;
}

export interface SchemaMeta {
  agent_id: string | null;
  app_version: string | null;
  created_at: number;
  meta_key: string;
  role: string;
  schema_version: number;
  updated_at: number;
}

export interface SessionTranscriptFiles {
  indexed_bytes: Generated<number>;
  leaf_id: string | null;
  mtime: Generated<number>;
  path: string;
  session_id: string;
  session_key: string;
  size: Generated<number>;
  updated_at: number;
}

export interface SessionTranscriptFts {
  message_id: string | null;
  role: string | null;
  session_id: string | null;
  session_key: string | null;
  text: string | null;
  timestamp: string | null;
}

export interface SessionTranscriptFtsConfig {
  k: string;
  v: string | null;
}

export interface SessionTranscriptFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  id: Generated<number>;
}

export interface SessionTranscriptFtsData {
  block: Uint8Array | null;
  id: Generated<number>;
}

export interface SessionTranscriptFtsDocsize {
  id: Generated<number>;
  sz: Uint8Array | null;
}

export interface SessionTranscriptFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface DB {
  auth_profile_state: AuthProfileState;
  auth_profile_store: AuthProfileStore;
  cache_entries: CacheEntries;
  memory_embedding_cache: MemoryEmbeddingCache;
  memory_index_chunks: MemoryIndexChunks;
  memory_index_meta: MemoryIndexMeta;
  memory_index_sources: MemoryIndexSources;
  memory_index_state: MemoryIndexState;
  schema_meta: SchemaMeta;
  session_transcript_files: SessionTranscriptFiles;
  session_transcript_fts: SessionTranscriptFts;
  session_transcript_fts_config: SessionTranscriptFtsConfig;
  session_transcript_fts_content: SessionTranscriptFtsContent;
  session_transcript_fts_data: SessionTranscriptFtsData;
  session_transcript_fts_docsize: SessionTranscriptFtsDocsize;
  session_transcript_fts_idx: SessionTranscriptFtsIdx;
}
